disabled_rules: # rule identifiers to exclude from running
  - todo
  - class_delegate_protocol
  - vertical_parameter_alignment

opt_in_rules: # some rules are only opt-in
  - force_unwrapping

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - mobile/ThirdPartyLibs

line_length: 175
#  warning: 175
#  error: 200

variable_name:
  min_length: 2

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
